
CREATE DATABASE QuanLyCuaHangTienLoi
GO

USE QuanLyCuaHangTienLoi
GO

CREATE TABLE tblCustomer
(
	cID INT IDENTITY PRIMARY KEY NOT NULL,
	cName NVARCHAR(100) NOT NULL,
	cAddress NVARCHAR(100) NOT NULL,
	cPhoneNumber NVARCHAR(100) NOT NULL,
	cEmail NVARCHAR(100)
)
GO

CREATE TABLE tblStaff
(
	sID INT IDENTITY PRIMARY KEY NOT NULL,
	sName NVARCHAR(100) NOT NULL,
	sGender NVARCHAR(100) NOT NULL,
	sAddress NVARCHAR(100) NOT NULL,
	sPhoneNumber NVARCHAR(15) NOT NULL,
	sBirthday DATETIME NOT NULL
)
GO

CREATE TABLE tblGoodsCategory
(
	id INT IDENTITY PRIMARY KEY,
	name NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE tblGoods
(
	gID INT IDENTITY PRIMARY KEY NOT NULL,
	categoryID INT NOT NULL,
	gName NVARCHAR(100) NOT NULL,
	gAmount FLOAT(50) NOT NULL,
	gPrice FLOAT(50) NOT NULL,
	gStatus INT NOT NULL DEFAULT 0 --1: con hang, 0: het hang

	FOREIGN KEY (categoryID) REFERENCES dbo.tblGoodsCategory(id)
)
GO


CREATE TABLE tblBill
(
	bID INT IDENTITY PRIMARY KEY,
	bDate DATETIME NOT NULL DEFAULT GETDATE(),
	sID INT NOT NULL,
	cID INT NOT NULL,

	FOREIGN KEY (sID) REFERENCES dbo.tblStaff(sID),
	FOREIGN KEY (cID) REFERENCES dbo.tblCustomer(cID)
)
GO

CREATE TABLE tblBillInfo
(
	ID INT IDENTITY PRIMARY KEY,
	bID INT NOT NULL,
	gID INT NOT NULL,
	gCount FLOAT(50) NOT NULL,
	Total FLOAT NOT NULL,

	FOREIGN KEY (bID) REFERENCES dbo.tblBill(bID),
	FOREIGN KEY (gID) REFERENCES dbo.tblGoods(gID)
)
GO

CREATE TABLE Account
(
	UserName NVARCHAR(100) PRIMARY KEY,	
	DisplayName NVARCHAR(100) NOT NULL ,
	PassWord NVARCHAR(1000) NOT NULL DEFAULT 123456,
	Type INT NOT NULL  DEFAULT 0 -- 1: admin && 0: staff
)
GO
